### ISSUE TITLE
Failing to start concrete5

### ISSUE THREAD

**Issue by J-tt** [chriswayg/concrete5.7#1]
(newbie here so please excuse errors)
I'm having a go at getting concrete5 running in a docker container and I'm following your commands letter by letter (besides changing mysql passwords) and it keeps failing on running concrete5 with this error:

`Error response from daemon: Could not get container for db`

Any ideas?

Running Linux Mint with i3 window manager.

**Comment by chriswayg** [comment]
Hi, 
 you followed the commands in the right way. I corrected the container name in

```
docker run -d --name db \
--restart=always \
--volumes-from c5_DATA_1 \
-e MYSQL_ROOT_PASSWORD=the_db_root_password \
-e MYSQL_USER=c5dbadmin \
-e MYSQL_PASSWORD=the_db_user_password \
-e MYSQL_DATABASE=c5db \
mariadb
```

so that `--link db:db` will find the database container. `db` will also be used as your server name during setup. I tested it, and it should work by copy/pasting the commands.

Just let me know how it works out for you.

Blessings,
Christian

**Comment by J-tt** [comment]
Thanks
